# Generated by Django 3.0.2 on 2020-04-01 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('auction', models.ForeignKey(db_column='auction', default=None, on_delete=django.db.models.deletion.CASCADE, to='auction.Auction')),
                ('bidding_user', models.ForeignKey(db_column='bidding_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auction_bidders',
            },
        ),
    ]
