# Generated by Django 3.0.3 on 2020-04-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidding',
            options={'ordering': ['-bidding_price']},
        ),
    ]
