# Generated by Django 3.0.2 on 2020-04-01 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_bid_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('auction_default_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('auction_status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('PENDING', 'PENDING')], default='PENDING', max_length=9)),
                ('auction_end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('auction_winner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(db_column='item', default=None, on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
            options={
                'db_table': 'auction',
            },
        ),
    ]
