# Generated by Django 3.0.3 on 2020-04-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_item_sold',
            field=models.BooleanField(default=False),
        ),
    ]
