# Generated by Django 3.0.3 on 2020-04-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auction_auction_item_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_bid_price',
        ),
    ]
